### ISSUE TITLE
Upsample Error

### ISSUE THREAD

**Issue by vinaykumarngitub** [htshinichi/caffe-onnx#10]
Still I am getting the error: After taking new scripts

pool4 节点构建完成
Failed at layer conv_decode4, layer's bottom not detected ...
添加参数conv_decode4_W输入信息和tensor数据
添加参数conv_decode4_b输入信息和tensor数据
Traceback (most recent call last):
  File "convert2onnx.py", line 34, in <module>
    main(args)
  File "convert2onnx.py", line 27, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master_new\src\caffe2onnx.py", line 28, in __init__
    self.__getNodeList(LayerList)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master_new\src\caffe2onnx.py", line 229, in __getNodeList
    conv_node = op.createConv(Layers[i],nodename,inname,outname,input_shape)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master_new\src\OPs\Conv.py", line 71, in createConv
    output_shape = getConvOutShape(input_shape, layer, dict)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master_new\src\OPs\Conv.py", line 49, in getConvOutShape
    h = (input_shape[0][2] - kernel_shape[0] + pads[0] + pads[2] - (kernel_shape[0]-1)*(dilations[0]-1))/strides[0] + 1 # 输出维度N= ((输入维度I - 卷积核维度K + 2 * 填充P - (卷积核维度-1)*(膨胀系数-1))/步长S) + 1

**Comment by vinaykumarngitub** [comment]
Failed at layer conv_decode4, layer's bottom not detected ...
The bottom layer of conv_decode4 is Upsample layer.

**Comment by ZQPei** [comment]
Sorry, I forget uncomment the code of `Upsample`.
You can uncomment those lines 367-385 in `src/caffe2onnx.py`.

Tell me if there is still error.

**Comment by vinaykumarngitub** [comment]
Ok sure. Thank you.

**Comment by vinaykumarngitub** [comment]
The above error is resolved.
But, I am not able to save the "onnx". I am getting the following warning:
 Op registered for Upsample is deprecated in domain_version of 11

==> Context: Bad node spec: input: "pool4_Y" input: "upsample4_Scale" output: "upsample4_Y" name: "upsample4" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }

**Comment by ZQPei** [comment]
downgrade your onnx to 1.4.0

**Comment by vinaykumarngitub** [comment]
It worked.!! Thank you.
