### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by kobenein** [htshinichi/caffe-onnx#12]
Traceback (most recent call last):
  File "convert2onnx.py", line 34, in <module>    main(args)
  File "convert2onnx.py", line 27, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "/home/kobenein/Downloads/caffe-onnx/src/caffe2onnx.py", line 29, in __init__
    self.__addOutputsTVIandValueInfo()
  File "/home/kobenein/Downloads/caffe-onnx/src/caffe2onnx.py", line 509, in __addOutputsTVIandValueInfo
    hid_out_tvi = helper.make_tensor_value_info(innernode.outputs_name[k], TensorProto.FLOAT,innernode.outputs_shape[k])
  File "/home/kobenein/.local/lib/python3.7/site-packages/onnx/helper.py", line 342, in make_tensor_value_info
    for i, d in enumerate(shape):
TypeError: 'int' object is not iterable

**Comment by ZQPei** [comment]
Is your onnx version `1.4.0`?

**Comment by kobenein** [comment]
Failed to install onnx 1.4.0, so I use 1.6.0

**Comment by ZQPei** [comment]
Downgrade your onnx to `1.4.0` by `pip uninstall onnx && pip install onnx==1.4.0`.
