### ISSUE TITLE
self.debug does not exist

### ISSUE THREAD

**Issue by LiyouZhou** [htshinichi/caffe-onnx#14]
https://github.com/htshinichi/caffe-onnx/blob/master/src/caffe2onnx.py#L481

run into an issue here that self.debug does not exist in the class.

**Comment by ucalyptus** [comment]
@LiyouZhou @htshinichi same issue here.

**Comment by ucalyptus** [comment]
@LiyouZhou I also tried removing the if else statement, 
But that gave me this 
添加参数upsample_16_W输入信息和tensor数据
添加参数upsample_16_b输入信息和tensor数据
upsample_16 节点构建完成
Failed at layer concat, layer's bottom not detected ...
Traceback (most recent call last):
  File "convert2onnx.py", line 34, in <module>
    main(args)
  File "convert2onnx.py", line 27, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "/content/caffe-onnx/src/caffe2onnx.py", line 28, in __init__
    self.__getNodeList(LayerList)
  File "/content/caffe-onnx/src/caffe2onnx.py", line 395, in __getNodeList
    Concat_node = op.createConcat(Layers[i], nodename, inname, outname, input_shape)
  File "/content/caffe-onnx/src/OPs/Concat.py", line 21, in createConcat
    output_shape = getConcatOutShape(input_shape)
  File "/content/caffe-onnx/src/OPs/Concat.py", line 12, in getConcatOutShape
    n,c,w,h = input_shape[0][0],0,input_shape[0][2],input_shape[0][3]
IndexError: list index out of range

**Comment by LiyouZhou** [comment]
workaround, delete these two lines. https://github.com/htshinichi/caffe-onnx/blob/master/src/caffe2onnx.py#L481-L482

**Comment by ucalyptus** [comment]
@LiyouZhou did, some other issue crept up.
