### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Note-Liu** [htshinichi/caffe-onnx#31]
the error meaasge:
添加参数conv5_1_W输入信息和tensor数据
conv5_1 节点构建完成
Failed at layer fc7, layer's bottom not detected ...
Traceback (most recent call last):
  File "convert2onnx.py", line 34, in <module>
    main(args)
  File "convert2onnx.py", line 27, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "/Documents/caffe-onnx/src/caffe2onnx.py", line 28, in __init__
    self.__getNodeList(LayerList)
  File "/Documents/caffe-onnx/src/caffe2onnx.py", line 433, in __getNodeList
    paramdata = op.getReshapeOutShape(Layers[i],reshape_input_shape)
  File "/Documents/caffe-onnx/src/OPs/Reshape.py", line 13, in getReshapeOutShape
    for dim in input_shape[0]:
IndexError: list index out of range
Hou to solve?

**Comment by sandeepy1** [comment]
Hello, If you have managed to solve it please tell.
