### ISSUE TITLE
Upsample : Key Error

### ISSUE THREAD

**Issue by vinaykumarngitub** [htshinichi/caffe-onnx#9]
I am trying to convert a caffemodel which consists of Upsample layer in it. But I am getting the following error : (scenario: I have un-commented the line numbers from 368-385 in caffe2onnx.py script)
Traceback (most recent call last):
  File "convert2onnx.py", line 42, in <module>
    main(args)
  File "convert2onnx.py", line 35, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master\src\caffe2onnx.py", line 28, in __init__
    self.__getNodeList(LayerList)
  File "D:\VinayKumar\Programs\Task8(TRT_SegNet)\caffe-onnx-master\src\caffe2onnx.py", line 377, in __getNodeList
    pname = self.__addInputsTVIfromMannul(Layers[i],op_pname["Upsample"],op_ptype["Upsample"],paramshape,paramdata)
KeyError: 'Upsample'

Please do the needful.
Thanks in advance.

**Comment by ZQPei** [comment]
I have fixed the problem.
`git pull origin master` and try again?
